services:
  db:
    image: postgres:16
    container_name: voting_db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb

    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: voting_backend
    environment:
      FLASK_CONFIG: ProductionConfig
      SECRET_KEY: "change-me"
      DATABASE_URL: "postgresql+psycopg2://appuser:apppass@db:5432/appdb"
      PORT: "5000"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "gunicorn -w 4 -b 0.0.0.0:5000 backend.run:app"

volumes:
  db_data:
