- name: Deploy Voting App
  hosts: voting
  become: true

  pre_tasks:
    - name: Ensure Python is installed (for Ansible facts)
      raw: |
        if ! command -v python3 >/dev/null 2>&1; then
          sudo apt-get update -y && sudo apt-get install -y python3
        fi
      changed_when: false

  vars:
    docker_image: "ghcr.io/{{ github_repo }}/voting-app:latest"
    db_url: "postgresql+psycopg2://{{ db_user }}:{{ db_pass }}@{{ rds_endpoint }}:{{ rds_port }}/{{ db_name }}"

  tasks:
    - name: Install Docker + Docker Compose + Deps.
      apt:
        name:
          - python3-pip
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Install Docker SDK for Python
      pip:
        name: docker
  
    - name: Create app directory
      file:
        path: /home/ubuntu/voting-app
        state: directory
        owner: ubuntu
        mode: '0755'

    - name: Create log directory
      file:
        path: /home/ubuntu/voting-app/logs
        state: directory
        owner: ubuntu
        mode: '0755'

    - name: Generate docker-compose.yaml
      copy:
        dest: /home/ubuntu/voting-app/docker-compose.yaml
        content: |
          version: '3'
          services:
            voting-app:
              image: {{ docker_image }}
              ports:
                - "80:5000"
              environment:
                DATABASE_URL: "{{ db_url }}"
    
    - name: Run Docker Compose
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: /home/ubuntu/voting-app

  handlers:
  - name: Restart Docker
    service:
      name: docker
      state: restarted