---
- name: Deploy Voting App
  hosts: voting
  become: true

  pre_tasks:
    - name: Ensure Python is installed (for Ansible facts)
      ansible.builtin.raw: |
        if ! command -v python3 >/dev/null 2>&1; then
          sudo apt-get update -y && sudo apt-get install -y python3
        fi
      changed_when: false

  vars:
    docker_image: "ghcr.io/{{ github_repo }}/voting-app:latest"
    db_url: "postgresql+psycopg2://{{ db_user }}:{{ db_pass }}@{{ rds_endpoint }}:{{ rds_port }}/{{ db_name }}"

  tasks:
    - name: Install Docker + Docker Compose + Dependencies
      ansible.builtin.apt:
        name:
          - python3-pip
          - docker.io
          - docker-compose
        state: present
        update_cache: true

    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: docker

    - name: Create app directory
      ansible.builtin.file:
        path: /home/ubuntu/voting-app
        state: directory
        owner: ubuntu
        mode: '0755'

    - name: Create log directory
      ansible.builtin.file:
        path: /home/ubuntu/voting-app/logs
        state: directory
        owner: ubuntu
        mode: '0755'

    - name: Generate docker-compose.yaml securely
      ansible.builtin.copy:
        dest: /home/ubuntu/voting-app/docker-compose.yaml
        owner: ubuntu
        mode: '0640'
        content: |
          version: '3'
          services:
            voting-app:
              image: {{ docker_image }}
              ports:
                - "5000:5000"
              environment:
                DATABASE_URL: "{{ db_url }}"

    - name: Check if voting app container exists
      ansible.builtin.command:
        cmd: docker ps -a --filter "name=voting-app" --format "{{ '{{.Names}}' }}"
      register: container_check
      changed_when: false

    - name: Set provisioning mode
      ansible.builtin.set_fact:
        first_provisioning: "{{ container_check.stdout == '' }}"

    - name: Stop and remove old container (only if updating)
      ansible.builtin.command:
        cmd: docker-compose down
        chdir: /home/ubuntu/voting-app
      when: not first_provisioning
      changed_when: true

    - name: Remove old image (only if unused and exists)
      ansible.builtin.command:
        cmd: docker image rm {{ docker_image }}
      when: not first_provisioning
      register: image_rm_result
      changed_when: image_rm_result.rc == 0
      failed_when: image_rm_result.rc != 0 and
                  "'No such image' not in image_rm_result.stderr and
                    'is using its referenced image' not in image_rm_result.stderr and
                    'image is being used by running container' not in image_rm_result.stderr"

    - name: Pull latest voting app image
      ansible.builtin.command:
        cmd: docker pull {{ docker_image }}
      changed_when: true

    - name: Run Docker Compose
      ansible.builtin.command:
        cmd: docker-compose up -d
        chdir: /home/ubuntu/voting-app
      changed_when: true

    - name: Get container ID of voting app
      ansible.builtin.command:
        cmd: >
          docker ps
          --filter "ancestor=ghcr.io/{{ github_repo }}/voting-app:latest"
          --format "{{ '{{.Names}}' }}"
      register: container_name
      changed_when: false

    - name: Seed the database
      ansible.builtin.command:
        cmd: docker exec {{ container_name.stdout }} python -m backend.seed
      when: seed_db | default(false)
      no_log: true  # Prevents logging DB seed output
      changed_when: false
      failed_when: container_name.stdout == ""

  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted
