- name: Deploy Voting App
  hosts: voting
  become: true

  vars:
    docker_image: "ghcr.io/{{ github_repo }}/voting-app:latest"
    db_url: "postgresql+psycopg2://{{ db_user }}:{{ db_pass }}@{{ rds_endpoint }}:{{ rds_port }}/{{ db_name }}"

  tasks:
    - name: Install Docker
      apt:
        name:
          - python3-pip
          - docker.io
        state: present
        update_cache: yes

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: install Docker Compose
      apt:
        name: docker-compose
        state: present
    
    - name: Create app directory
      file:
        path: /home/ubuntu/voting-app
        state: directory
        owner: ubuntu
        mode: '0755'
    
    - name: Generate docker-compose.yaml
      copy:
        dest: /home/ubuntu/voting-app/docker-compose.yaml
        content: |
          version: '3'
          services:
            voting-app:
              image: {{ docker_image }}
              ports:
                - "80:5000"
              environment:
                DATABASE_URL: "{{ db_url }}"
    
    - name: Run Docker Compose
      command: docker compose up -d
      args:
        chdir: /home/ubuntu/voting-app
