name: CD

on: 
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      packages: read # Allows to pull Docker image from GHCR

    steps:
      # 1. Checkout the repos
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. Configure AWS credentials (GitHub Actions)
      - name: Configure AWS credentials
        if: ${{ !env.ACT }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Test AWS credentials
        run: aws sts get-caller-identity