name: CI

on:
  pull_request:
    branches: ["*"]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    services:
      postgres:
        image: postgres:16
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: voting
        options: >-
          --health-cmd pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # 1. checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install flake8

      # 4. lint Python code
      - name: Lint backend (flake8)
        run: |
          flake8 backend

      # 5. Wait for Postgres to be ready
      - name: Wait for Postgres to be ready
        run: |
            for i in {1..10}; do
            pg_isready -h localhost -p 5432 && break
            echo "Waiting for Postgres..."
            sleep 2
            done

      # 6. run tests
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/voting
          FLASK_CONFIG: TestingConfig
        run: pytest -v

      # 7. Terraform Init
      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init -backend=false

      # 8. Lint Terraform
      - name: Terraform Linting
        working-directory: infra/terraform
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: infra/terraform
        run: terraform validate

      # 9. Terraform Plan
      - name: Terraform Plan
        working-directory: infra/terraform
        run: terraform plan -detailed-exitcode || true

      # 10. Login Github Container Registry (ghcr.io)
      - name: Log in registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      # 11. Login Github Container Registry (ghcr.io
      - name: Set lowercase repo slug
        run: echo "REPO_SLUG=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # 12. build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_SLUG }}/voting-app:latest
