name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'Destroy-prod' to confirm"
        required: true
        default: "Cancel"

jobs:
    destroy:
      runs-on: ubuntu-latest
      if: github.event.inputs.confirm == 'Destroy-prod'

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.13.0

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Initialize Terraform
          working-directory: infra/terraform
          run: terraform init -reconfigure -input=false -no-color

        - name: Generate Destroy Plan
          working-directory: infra/terraform
          run: terraform plan -destroy -input=false -no-color -lock=false

        - name: Final Confirmation Delay
          run: |
            echo " --> DESTRUCTION WILL START IN 15 SECs..."
            echo " --> CANCELNOW IF THIS IS A MISTAKE!"
            sleep 15

        - name: Infrastructure Destruction
          working-directory: terraform
          run: terraform destroy -auto-approve -input=false -no-color -lock=false

        - name: Backup Terraform State
          run: |
            echo "Creating State Backup Before cleanup..."
            aws s3 cp s3://my-terraform-state-bucket-he1/voting-app/terraform-tfstate \
              s3://my-terraform-state-bucket-he1/voting-app/terraform.tfstate.$(date +%Y%m%d-%H%M%S).backup

        - name: Clean S3 State (Optional)
          if: success()
          run: |
            echo "Removing Terraform state file from S3..."
            aws s3 rm s3://my-terraform-state-bucket-he1/voting-app/terraform.tfstate
            echo "State file removed successfully."

        - name: Verify Destruction Completion
          run: |
            echo " --> Destruction completed successfully"
            echo " --> State backed up to S3 backups/"
            echo " --> Infrastructure resources have been destroyed"